### ISSUE TITLE
Receiving Connection Refused error when running server

### ISSUE THREAD

**Issue by sadsa** [cofinley/FluentForeverVocabBuilder#3]
Has anyone seen this error when trying to run the static site?

`Traceback (most recent call last):
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/app/routes.py", line 16, in index
    decks = ac.get_deck_names()
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/app/service/anki_connect.py", line 32, in get_deck_names
    return self.invoke("deckNames")
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/app/service/anki_connect.py", line 20, in invoke
    response = requests.request("POST", self.URL, json=payload).json()
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/joshbiddick/Projects/FluentForeverVocabBuilder/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8765): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x108617b90>: Failed to establish a new connection: [Errno 61] Connection refused'))
127.0.0.1 - - [04/Aug/2019 11:31:46] "GET / HTTP/1.1" 500 -`

**Comment by sadsa** [comment]
OK, looks like I just needed to restart ANKI after installing the AnkiConnect Add-on.
